---
title: "Group Lab 2. Mapping Origin-Destination Data on Employment and Industry in the US"
author: "Group 6 (Xinbo Lu, Wenjin Yu, Jody Tran, Doyle Park, Abraham Im)"
date: "January 28, 2019"
output: html_document
---
##Part 2 Preparing Data
###OD Data
For this step, the purpose is to aggregate each work type, for example, S000 and SA01, and then trim the sum of each work type to fit in the King County census tract 2010. 

```{r , message=FALSE, warning=FALSE, echo=FALSE}
library(dplyr)
## read the od csv, and clean up formatting issues
t = read.csv("wa_od_main_JT00_2015.csv")
t$w_geocode<-as.character(t$w_geocode)
t$h_geocode<-as.character(t$h_geocode)
t$w_geocode[which(length(t$w_geocode) == 14)]<-paste0("0",t$w_geocode[which(length(t$w_geocode) == 14)])
t$h_geocode[which(length(t$h_geocode) == 14)]<-paste0("0",t$h_geocode[which(length(t$h_geocode) == 14)])


##Making Columns for worktract and hometract
t$wt<-substr(t$w_geocode,1,11)
t$ht<-substr(t$h_geocode,1,11)

##Aggregating each work type
type_S000 = aggregate(. ~ wt + ht,data=t[,c(3,14,15)],FUN=sum)
type_SA01 = aggregate(. ~ wt + ht,data=t[,c(4,14,15)],FUN=sum)
type_SA02 = aggregate(. ~ wt + ht,data=t[,c(5,14,15)],FUN=sum)
type_SA03= aggregate(. ~ wt + ht,data=t[,c(6,14,15)],FUN=sum)
type_SE01 = aggregate(. ~ wt + ht,data=t[,c(7,14,15)],FUN=sum)
type_SE02 = aggregate(. ~ wt + ht,data=t[,c(8,14,15)],FUN=sum)
type_SE03 = aggregate(. ~ wt + ht,data=t[,c(9,14,15)],FUN=sum)
type_SI01 = aggregate(. ~ wt + ht,data=t[,c(10,14,15)],FUN=sum)
type_SI02 = aggregate(. ~ wt + ht,data=t[,c(11,14,15)],FUN=sum)
type_SI03 = aggregate(. ~ wt + ht,data=t[,c(12,14,15)],FUN=sum)

##using a df to store the aggregated work type
pre_OD_worktype_tract <- data.frame(type_S000, type_SA01, type_SA02, type_SA03, type_SE01, type_SE02, type_SE03, type_SI01, type_SI02, type_SI03)

##clean up duplicated wt and ht
OD_worktype_tract <- pre_OD_worktype_tract %>%
  select(-contains("t."))

##Importing King Country tract list 
kc <- read.csv("kcTract10.csv")

##change GEOID to wt for the joining/merging process
names(kc)[5] <- ("wt")


##Merging to cut dataset down to just KC tracts
kc_OD=merge(kc,OD_worktype_tract,by="wt")

##clean formatting issues
kc_OD$wt<- as.character(kc_OD$wt)
kc_OD$wt[which(length(kc_OD$wt) == 14)]<-paste0("0",kc_OD$wt[which(length(kc_OD$wt) == 14)])

##output csv 
#write.csv(kc_OD, "OD2015_Alljobs.csv")
```


```{r , message=FALSE, warning=FALSE, echo=TRUE}
## FOR WAC CSV
##Setting up table and cleaning up
w = read.csv("wa_wac_S000_JT00_2015.csv")
w$w_geocode<-as.character(w$w_geocode)
w$w_geocode[which(length(w$w_geocode) == 14)]<-paste0("0",w$w_geocode[which(length(w$w_geocode) == 14)])


##Making Columns for worktract and hometract
w$wt<-substr(w$w_geocode,1,11)


##Aggregating
wtuwac=aggregate(. ~ w$wt,data=w[,c(2,11,13,14,16)],FUN=sum)
colnames(wtuwac)[colnames(wtuwac)=="w$wt"] <- "GEOID"


##Merge w/ King County Tract
kc=read.csv("kcTract10.csv")
names(kc)[1]=paste("wt")
kc$GEOID10<-as.character(kc$GEOID10)
colnames(kc)[colnames(kc)=="GEOID10"] <- "GEOID"
wackc=merge(kc,wtuwac,by="GEOID")


##Adding Combined UMWT (utilities, manufacturing, wholesale trade, and transportation & warehouseing)
wackc["UMWT"]=wackc$CNS03+wackc$CNS05+wackc$CNS06+wackc$CNS08
wackc["UMWTshare"]=wackc$UMWT/wackc$C000

#write.csv(wackc,"wac2015_Alljobs.csv")
```


```{r , message=FALSE, warning=FALSE, echo=TRUE}
## FOR RAC CSV
##Setting up table and cleaning up
r = read.csv("wa_rac_S000_JT00_2015.csv")
r$h_geocode<-as.character(r$h_geocode)
r$h_geocode[which(length(r$h_geocode) == 14)]<-paste0("0",r$h_geocode[which(length(r$h_geocode) == 14)])


##Making Columns for worktract and hometract
r$rt<-substr(r$h_geocode,1,11)


##Aggregating
rturac=aggregate(. ~ r$rt,data=r[,c(2,11,13,14,16)],FUN=sum)
colnames(rturac)[colnames(rturac)=="r$rt"] <- "GEOID"


##Merge w/ King County Tract
names(kc)[1]=paste("rt")
rackc=merge(kc,rturac,by="GEOID")


##Adding Combined UMWT (utilities, manufacturing, wholesale trade, and transportation & warehouseing)
rackc["UMWT"]=rackc$CNS03+rackc$CNS05+rackc$CNS06+rackc$CNS08
rackc["UMWTshare"]=rackc$UMWT/rackc$C000

#write.csv(rackc,"rac2015_Alljobs.csv")
```


##Part 3
###Step6
```{r echo=FALSE, warning=FALSE, message=FALSE, fig.width=12, fig.height=12}
##Calculate Location Quotients (Links to an external site.)Links to an external site. for all of your data, and then "zoom in" to look at the location quotients for the subset of tracts selected from your OD data.
library(maptools)
library(RColorBrewer)
library(tmap)
kcTract<- readShapeSpatial('C:/Users/LXB19/Documents/GEOG458/Lab2/kc_shp/king10ct')
OD<- read.csv("OD2015_Alljobs.csv")
names(kcTract)

##extract the attribute data of instrest, in this case, it is the percentage of "Number of jobs of workers age 29 or younger" and the "Total Number of jobs", SA01/S000

SA01 <- OD$SA01
S000 <- OD$S000

LQ <- function(SA01, S000){
  sdp <- SA01/S000
  dp <- sum(SA01) / sum(S000)
  sdp/dp
}


kc_LQ <- data.frame(OD$wt, LQ(SA01, S000))
colnames(kc_LQ) <- c("wt", "kc_LQ")
brks<-c(0.5,1,1.5,2,2.5,3,3.5,4,4.5,5)

colours <- brewer.pal(10, "Blues") 

kc_LQPlot <- plot(kcTract, col=colours[findInterval(kc_LQ$kc_LQ, brks, all.inside=TRUE)], axes=F)
box()
title(paste("LQ of SA01 and S000"))
legend("bottomright", legend=leglabs(brks), fill=colours, bty="n", border = "black", title = "Percent of workers <= 29")

```
